#ifndef _SERVER_CODES_H_
#define _SERVER_CODES_H_

#define SERV_SUCCESS 200
#define SERV_SUCCESS_CREATED 201
#define SERV_OK 0
#define SERV_BAD_REQUEST 400
#define SERV_FORBIDDEN 403
#define SERV_NOT_FOUND 404

#endif // SERVER_CODES_H
